version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crudapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: jcanotorr06/crud_django
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "bash", "launch.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=crudapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db